Quaternion lqr
jmpark418/fault-tolerant-control pull request #1
Opened 2023-09-22 06:34 UTC by jmpark418

added controller_quater.py and quater.py

quadrotor quaternion control and LPF for omega_d calculation

2023-09-22 06:35 UTC, hnlee77 commented on ftc/models/multicopter.py
> +    def __init__(self, env_config={}, dx=0.0, dy=0.0, dz=0.0, rtype="quad"):
```suggestion
    def __init__(self, env_config={}, dx=0.0, dy=0.0, dz=0.0, rtype="hexa-x"):
```

2023-09-22 06:36 UTC, hnlee77 commented on ftc/models/multicopter.py
> +    def __init__(self, env_config={}, dx=0.0, dy=0.0, dz=0.0, rtype="quad"):
여길 수정하지 않아도 된답니다~!

2023-09-22 06:36 UTC, hnlee77 commented on examples/controller_pid.py
> +        self.plant = Multicopter(env_config["plant"])
```suggestion
        self.plant = Multicopter(env_config["plant"], rtype="quad")
```

2023-09-22 06:37 UTC, hnlee77 commented on examples/controller_pid.py
> +        self.plant = Multicopter(env_config["plant"])
보통 main파일에서 정의해주는게 좋습니다~!

2023-09-22 06:39 UTC, hnlee77 commented on examples/controller_lqr.py
> +
```suggestion
    
    
```

2023-09-22 06:42 UTC, hnlee77 commented on examples/controller_quater.py
> +    # ylabels = np.array((["R1", "R2"], ["R3", "R4"], ["R5", "R6"]))
필요없는 부분은 다 지워줍시다 그냥~

2023-09-22 06:43 UTC, hnlee77 commented on ftc/controllers/PID/pid.py
> +        angd = np.deg2rad(np.vstack((0, 0, 0)))
`PID` 위치제어기도 추가해줘 봅시다~

2023-09-22 06:44 UTC, hnlee77 commented on examples/controller_pid.py
> +    ylabels = np.array((["R1", "R2"], ["R3", "R4"], ["R5", "R6"]))
쿼드콥터에 맞게 바꿔줘야 할 듯~

2023-09-22 06:47 UTC, hnlee77 requested changes
위 코멘트들만 우선 반영해 볼까요?

### 참고
위 코멘트들 중 `suggested change` 가 있는 부분은 제안이 마음에 든다면 웹에서 `Commit suggestion`을 누르면 바로 반영이 됩니다. 그런데 이는 원격레포 상에서 반영이 되는 것으로 로컬에서 반드시 `fetch`와 `pull`을 해야 반영된 사항을 확인할 수 있습니다!

2023-09-22 07:05 UTC, hnlee77 commented on ftc/controllers/PID/pid.py
> +        angd = np.deg2rad(np.vstack((0, 0, 0)))
[이 논문](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=5520914) 참고!

2023-10-09 17:37 UTC, hnlee77 commented
오 PID 제어기도 아주 잘 짰네~!
우선 코드 포맷을 통일하기 위해서 아래와 같이 실행 후 다시 push 부탁드려요~
- 아래와 같이 conda 가상환경에 `black/isort` 설치
```
(venv)$ conda install black isort
```
- 새로 작성한 파일에 아래와 같이 적용
```
(venv)$ black **/*.py
(venv)$ isort **/*.py
```

2023-10-10 02:24 UTC, jmpark418 commented
formatting 후 다시 push 했습니다~!
확인 부탁드립니다!

2023-10-11 05:18 UTC, hnlee77 commented
종민아 `examples/controller_lqr.py` 도 formatting 한번 부탁해~
나머지는 아주 좋음!

2023-10-11 05:27 UTC, hnlee77 commented on ftc/controllers/PID/pid.py
> +        self.ang_int.dot = ang
이 부분은 지금은 regulation이라 문제 없겠지만 혹시 desired position 등이 주어지는 tracking에서도 문제가 없으려면 `pos_e`, `ang_e`를 적분하도록 바꾸는게 맞겠어요!

2023-10-11 05:29 UTC, hnlee77 commented on ftc/controllers/PID/pid.py
> +import fym
이상한 논문을 오려놨는데 알아서 잘 찾아서 위치제어기까지 잘 짰네? ㅋㅋㅋ (참고한 논문을 위쪽에 인용해주면 좋겠습니다)

2023-10-11 05:33 UTC, hnlee77 commented on ftc/controllers/Quater/quater.py
> +        self.thetadf.dot = thetadf_dot
LPF 를 이용해서  differentiator (위에서 사용한 수치 미분 방법) 외에도 actuator dynamics (조금 더 느리게 따라가도록) 등을 구현할 수 있어요 ㅎㅎ (참고용)

2023-10-11 10:58 UTC, jmpark418 commented on ftc/controllers/PID/pid.py
> +import fym
Notation이 헷갈려서... 찾아서 해봤습니다 ㅎㅎ

2023-10-12 04:48 UTC, hnlee77 approved these changes
좋습니다~! 머지해도 될 듯 ㅎㅎ

2023-10-12 06:52 UTC, merged